# Form implementation generated from reading ui file 'C:\Users\ASUS\Documents\Python_LTI\New folder\untitled.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 328)
        Form.setStyleSheet("   background-color: #1b1b2f; /* Dark background */\n"
"    color: #ffffff; /* Default text color */\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 14px;")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setStyleSheet("  color: #00d9ff; /* Neon cyan text */\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    padding: 5px;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(parent=Form)
        self.spinBox.setStyleSheet("QSpinBox {\n"
"    background-color: #0f0f14;\n"
"    color: #00d9ff;\n"
"    border: 2px solid #00d9ff;\n"
"    border-radius: 8px;\n"
"    padding: 4px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"QSpinBox::up-button, QSpinBox::down-button {\n"
"    background-color: #00d9ff;\n"
"    border: none;\n"
"    width: 16px;\n"
"}\n"
"QSpinBox::up-button:hover, QSpinBox::down-button:hover {\n"
"    background-color: #005f80;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 1, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(parent=Form)
        self.checkBox.setStyleSheet("QCheckBox {\n"
"    color: #00d9ff;\n"
"    font-size: 14px;\n"
"    spacing: 8px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    background-color: #1b1b2f;\n"
"    border: 2px solid #00d9ff;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #00d9ff;\n"
"    border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #ffffff;\n"
"}")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 2, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_2.setStyleSheet("QCheckBox {\n"
"    color: #00d9ff;\n"
"    font-size: 14px;\n"
"    spacing: 8px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    background-color: #1b1b2f;\n"
"    border: 2px solid #00d9ff;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #00d9ff;\n"
"    border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #ffffff;\n"
"}")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 3, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_3.setStyleSheet("QCheckBox {\n"
"    color: #00d9ff;\n"
"    font-size: 14px;\n"
"    spacing: 8px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    background-color: #1b1b2f;\n"
"    border: 2px solid #00d9ff;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #00d9ff;\n"
"    border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #ffffff;\n"
"}")
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 4, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_4.setStyleSheet("QCheckBox {\n"
"    color: #00d9ff;\n"
"    font-size: 14px;\n"
"    spacing: 8px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    background-color: #1b1b2f;\n"
"    border: 2px solid #00d9ff;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #00d9ff;\n"
"    border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #ffffff;\n"
"}")
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 5, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #00d9ff;\n"
"    color: #0f0f14;\n"
"    border: 2px solid #00f0ff;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    transition: 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005f80;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0088cc;\n"
"    border: 2px solid #ffffff;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setStyleSheet("/* QLineEdit Styles */\n"
"QLineEdit {\n"
"    background-color: #0f0f14; /* Dark background for input */\n"
"    color: #00d9ff; /* Neon cyan text color */\n"
"    border: 2px solid #00d9ff; /* Neon border */\n"
"    border-radius: 8px; /* Rounded corners for a smooth, modern look */\n"
"    padding: 8px; /* Padding inside the input box */\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    selection-background-color: #005f80; /* Selection background for text */\n"
"    selection-color: #ffffff; /* Color of selected text */\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid #ffffff; /* Change border to white on hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00ffcc; /* Glowing effect for focused state */\n"
"    background-color: #0f1f2f; /* Slightly brighter background when focused */\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #1b1b2f; /* Darker background for disabled */\n"
"    color: #555555; /* Greyed out text */\n"
"    border: 2px solid #555555; /* Greyed out border */\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 7, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #00d9ff;\n"
"    color: #0f0f14;\n"
"    border: 2px solid #00f0ff;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    transition: 0.3s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005f80;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0088cc;\n"
"    border: 2px solid #ffffff;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 8, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Pilih panjang password dan karakter yang ingin disertakan"))
        self.checkBox.setText(_translate("Form", "Huruf kecil (a-z)"))
        self.checkBox_2.setText(_translate("Form", "Huruf besar (A-Z)"))
        self.checkBox_3.setText(_translate("Form", "Angka (0-9)"))
        self.checkBox_4.setText(_translate("Form", "Simbol (!@#$%)"))
        self.pushButton.setText(_translate("Form", "Generate"))
        self.pushButton_2.setText(_translate("Form", "Salin ke Clipboard"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
